version: "3"

tasks:
  default:
    desc: Run all checks (same as CI)
    cmds:
      - task: fmt:check
      - task: clippy
      - task: test
      - task: doc

  fmt:
    desc: Format code with rustfmt
    cmds:
      - cargo fmt --all

  fmt:check:
    desc: Check code formatting
    cmds:
      - cargo fmt --all -- --check

  clippy:
    desc: Run clippy linter
    cmds:
      - cargo clippy --all-targets --all-features

  test:
    desc: Run all tests
    cmds:
      - cargo test --all

  doc:
    desc: Build documentation
    cmds:
      - cargo doc --no-deps --all-features
    env:
      RUSTDOCFLAGS: -Dwarnings

  build:
    desc: Build in debug mode
    cmds:
      - cargo build

  build:release:
    desc: Build in release mode
    cmds:
      - cargo build --release

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  pre-commit:install:
    desc: Install pre-commit hooks
    cmds:
      - pre-commit install

  pre-commit:run:
    desc: Run pre-commit on all files
    cmds:
      - pre-commit run --all-files
