version: "3"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  check:
    desc: Run all checks (same as CI)
    cmds:
      - task: fmt:check
      - task: clippy
      - task: test
      - task: doc

  fmt:
    desc: Format code with rustfmt
    cmds:
      - cargo fmt --all

  fmt:check:
    desc: Check code formatting
    cmds:
      - cargo fmt --all -- --check

  clippy:
    desc: Run clippy linter
    cmds:
      - cargo clippy --all-targets --all-features

  test:
    desc: Run unit tests (excludes e2e)
    cmds:
      - cargo test

  doc:
    desc: Build documentation
    cmds:
      - cargo doc --no-deps --all-features
    env:
      RUSTDOCFLAGS: -Dwarnings

  build:
    desc: Build in debug mode
    cmds:
      - cargo build

  build:release:
    desc: Build in release mode
    cmds:
      - cargo build --release

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  pre-commit:install:
    desc: Install pre-commit hooks
    cmds:
      - pre-commit install

  pre-commit:run:
    desc: Run pre-commit on all files
    cmds:
      - pre-commit run --all-files

  # E2E Tests
  e2e:
    desc: Run E2E tests with both transports (requires Docker)
    deps: [build]
    cmds:
      - task: e2e:gitlab:up
      - task: e2e:wait
      - task: e2e:runner:setup
      - task: e2e:pat:create
      - defer: { task: e2e:gitlab:down }
      - defer: { task: e2e:pat:cleanup }
      - cargo test -p tanuki-mcp-e2e -- --test-threads=1

  e2e:stdio:
    desc: Run E2E tests with stdio transport only
    deps: [build]
    cmds:
      - task: e2e:gitlab:up
      - task: e2e:wait
      - task: e2e:runner:setup
      - task: e2e:pat:create
      - defer: { task: e2e:gitlab:down }
      - defer: { task: e2e:pat:cleanup }
      - cargo test -p tanuki-mcp-e2e -- --test-threads=1 stdio

  e2e:http:
    desc: Run E2E tests with HTTP transport only
    deps: [build]
    cmds:
      - task: e2e:gitlab:up
      - task: e2e:wait
      - task: e2e:runner:setup
      - task: e2e:pat:create
      - defer: { task: e2e:gitlab:down }
      - defer: { task: e2e:pat:cleanup }
      - cargo test -p tanuki-mcp-e2e -- --test-threads=1 http

  e2e:gitlab:up:
    desc: Start GitLab CE container for E2E tests
    cmds:
      - docker compose -f e2e/docker-compose.yml up -d
    status:
      - docker inspect tanuki-mcp-e2e-gitlab --format '{{.State.Running}}' 2>/dev/null | grep -q true

  e2e:gitlab:down:
    desc: Stop GitLab CE container
    cmds:
      - docker compose -f e2e/docker-compose.yml down -v

  e2e:gitlab:logs:
    desc: Show GitLab container logs
    cmds:
      - docker compose -f e2e/docker-compose.yml logs -f gitlab

  e2e:wait:
    desc: Wait for GitLab to be ready (may take 3-5 minutes)
    cmds:
      - |
        echo "Waiting for GitLab to be ready (this may take 3-5 minutes)..."
        until curl -sf http://localhost:8080/users/sign_in >/dev/null 2>&1; do
          echo "  Still waiting..."
          sleep 10
        done
        echo "GitLab is ready!"

  e2e:runner:setup:
    desc: Setup GitLab runner (create token, register, start)
    cmds:
      - |
        echo "Setting up GitLab runner..."

        # Create runner token via Rails console
        echo "Creating runner token..."
        TOKEN=$(docker exec tanuki-mcp-e2e-gitlab gitlab-rails runner "
          Ci::Runner.where(description: 'e2e-runner').destroy_all
          runner = Ci::Runner.create!(
            runner_type: :instance_type,
            description: 'e2e-runner',
            run_untagged: true,
            active: true
          )
          puts runner.token
        " 2>/dev/null | tail -1)

        if [ -z "$TOKEN" ]; then
          echo "ERROR: Failed to create runner token"
          exit 1
        fi
        echo "Created runner token"

        # Unregister any existing runners
        docker exec tanuki-mcp-e2e-gitlab-runner gitlab-runner unregister --all-runners 2>/dev/null || true

        # Register the runner
        echo "Registering runner..."
        docker exec tanuki-mcp-e2e-gitlab-runner gitlab-runner register \
          --non-interactive \
          --url http://gitlab:80 \
          --token "$TOKEN" \
          --executor shell \
          --description "e2e-shell-runner"

        # Start the runner daemon in background
        echo "Starting runner daemon..."
        docker exec -d tanuki-mcp-e2e-gitlab-runner gitlab-runner run

        # Wait for runner to connect
        sleep 2
        echo "GitLab runner setup complete!"

  e2e:pat:create:
    desc: Create a shared PAT for e2e tests (speeds up tests)
    cmds:
      - |
        echo "Creating shared PAT for e2e tests..."
        TOKEN=$(docker exec tanuki-mcp-e2e-gitlab gitlab-rails runner "
          user = User.find_by(username: 'root')
          # Revoke existing shared token if present
          user.personal_access_tokens.find_by(name: 'e2e-shared-token')&.revoke!
          # Create new token
          token = user.personal_access_tokens.create!(
            name: 'e2e-shared-token',
            scopes: ['api', 'read_user', 'read_repository', 'write_repository'],
            expires_at: 1.day.from_now
          )
          puts token.token
        " 2>/dev/null | tail -1)

        if [ -z "$TOKEN" ]; then
          echo "ERROR: Failed to create shared PAT"
          exit 1
        fi

        echo "$TOKEN" > .e2e-token
        echo "Shared PAT saved to .e2e-token"

  e2e:pat:cleanup:
    desc: Remove shared PAT file
    cmds:
      - rm -f .e2e-token

  e2e:status:
    desc: Check GitLab container status
    cmds:
      - docker compose -f e2e/docker-compose.yml ps
      - |
        if curl -sf http://localhost:8080/users/sign_in >/dev/null 2>&1; then
          echo "GitLab is healthy and ready"
        else
          echo "GitLab is not ready yet"
        fi
